export default function Infopage() {
    return(
        <>
        <h3>This is the infopage placeholder</h3>

        <p>This is my Github Pages page, it is written in .jsx and uses React.</p>
        <p>The routing is done using the Hashrouter to make it work on Github.</p>
        
        <p><b>Random text:</b></p>
        <p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in gravida lacus. Etiam quam nulla, mollis ac leo in, finibus tristique augue. Duis ornare sapien vitae nisl elementum bibendum. Curabitur vitae augue egestas nisl varius tincidunt eu non ante. Donec eu nibh dignissim, tincidunt justo eu, tincidunt dui. Donec ut ligula eget elit volutpat lobortis. Duis vitae mauris tortor. Nullam sit amet aliquam leo. Nulla condimentum quam sit amet risus volutpat laoreet. Donec facilisis rutrum magna non vehicula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque consequat suscipit velit. Ut id mauris in sem aliquet ornare et efficitur risus. Pellentesque id tortor elit. Phasellus scelerisque nunc quis nisl convallis accumsan.

Donec finibus lacinia euismod. Donec iaculis ligula quis tristique iaculis. Aliquam eget mauris arcu. Duis ac arcu sapien. Vestibulum eget elit est. Aenean a libero risus. Etiam vitae interdum lectus. Fusce sit amet dui augue. Nullam vehicula ex enim, eget interdum turpis aliquam nec. Cras ultricies odio dolor, consectetur volutpat nulla pretium eget. Nam sit amet mauris metus. Ut sit amet facilisis metus. Fusce tortor tellus, consectetur ac aliquet eget, pulvinar ultrices libero. Donec ac mi lorem.

Ut eu ipsum imperdiet ipsum ornare facilisis. Mauris vitae tempor dui, eget tincidunt velit. Proin lorem neque, tempor sit amet neque sit amet, molestie tristique mauris. Vivamus eu elit et ipsum volutpat maximus. Suspendisse tincidunt diam ac magna dictum, id hendrerit mi hendrerit. Sed non fringilla enim, at aliquet odio. Curabitur velit tellus, porttitor ac congue at, euismod at ante. Cras id dignissim purus. Morbi sem ipsum, tempus ut leo eget, aliquet tincidunt risus. Aenean at egestas ligula, vel ullamcorper ex. Nunc eget viverra lectus, eget tristique mi. Vivamus eros libero, venenatis quis posuere ac, placerat sit amet libero. Ut non feugiat nunc. Sed tincidunt nibh ex, in semper ipsum facilisis sit amet. Aenean tempor, turpis vel elementum suscipit, libero eros aliquam urna, fermentum mattis quam leo laoreet nulla.

Mauris in enim ac ligula efficitur faucibus. Vestibulum nec diam eu nunc porttitor faucibus eu rutrum nibh. In pharetra magna aliquam enim iaculis, vel posuere diam blandit. Cras feugiat purus a nisi faucibus interdum. Donec condimentum ex rhoncus enim rutrum, eget eleifend erat dapibus. Nulla facilisi. Mauris tristique viverra mi eu hendrerit. Nam ullamcorper sem vel dui tincidunt auctor.

Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in gravida lacus. Etiam quam nulla, mollis ac leo in, finibus tristique augue. Duis ornare sapien vitae nisl elementum bibendum. Curabitur vitae augue egestas nisl varius tincidunt eu non ante. Donec eu nibh dignissim, tincidunt justo eu, tincidunt dui. Donec ut ligula eget elit volutpat lobortis. Duis vitae mauris tortor. Nullam sit amet aliquam leo. Nulla condimentum quam sit amet risus volutpat laoreet. Donec facilisis rutrum magna non vehicula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque consequat suscipit velit. Ut id mauris in sem aliquet ornare et efficitur risus. Pellentesque id tortor elit. Phasellus scelerisque nunc quis nisl convallis accumsan.

Donec finibus lacinia euismod. Donec iaculis ligula quis tristique iaculis. Aliquam eget mauris arcu. Duis ac arcu sapien. Vestibulum eget elit est. Aenean a libero risus. Etiam vitae interdum lectus. Fusce sit amet dui augue. Nullam vehicula ex enim, eget interdum turpis aliquam nec. Cras ultricies odio dolor, consectetur volutpat nulla pretium eget. Nam sit amet mauris metus. Ut sit amet facilisis metus. Fusce tortor tellus, consectetur ac aliquet eget, pulvinar ultrices libero. Donec ac mi lorem.

Ut eu ipsum imperdiet ipsum ornare facilisis. Mauris vitae tempor dui, eget tincidunt velit. Proin lorem neque, tempor sit amet neque sit amet, molestie tristique mauris. Vivamus eu elit et ipsum volutpat maximus. Suspendisse tincidunt diam ac magna dictum, id hendrerit mi hendrerit. Sed non fringilla enim, at aliquet odio. Curabitur velit tellus, porttitor ac congue at, euismod at ante. Cras id dignissim purus. Morbi sem ipsum, tempus ut leo eget, aliquet tincidunt risus. Aenean at egestas ligula, vel ullamcorper ex. Nunc eget viverra lectus, eget tristique mi. Vivamus eros libero, venenatis quis posuere ac, placerat sit amet libero. Ut non feugiat nunc. Sed tincidunt nibh ex, in semper ipsum facilisis sit amet. Aenean tempor, turpis vel elementum suscipit, libero eros aliquam urna, fermentum mattis quam leo laoreet nulla.

Mauris in enim ac ligula efficitur faucibus. Vestibulum nec diam eu nunc porttitor faucibus eu rutrum nibh. In pharetra magna aliquam enim iaculis, vel posuere diam blandit. Cras feugiat purus a nisi faucibus interdum. Donec condimentum ex rhoncus enim rutrum, eget eleifend erat dapibus. Nulla facilisi. Mauris tristique viverra mi eu hendrerit. Nam ullamcorper sem vel dui tincidunt auctor.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi hendrerit sollicitudin mauris, viverra gravida diam viverra ac. Donec eleifend mauris eget bibendum lacinia. Nulla pulvinar elementum risus. Mauris hendrerit gravida arcu, sit amet ultrices libero tincidunt et. Suspendisse hendrerit urna eget risus commodo porta. Vestibulum semper lorem eu urna ultrices, vel rhoncus elit feugiat. Praesent cursus velit gravida ante porttitor, sed tempor nisl tristique. Vivamus sit amet rhoncus orci, eu porttitor quam. Aenean vitae mi placerat metus posuere imperdiet quis quis risus. Maecenas at efficitur lectus. Proin eget leo volutpat mauris laoreet posuere a in lacus. Donec massa libero, condimentum non tellus quis, ornare molestie libero. Donec mattis ante non fringilla posuere. Suspendisse sagittis semper neque vitae finibus. Pellentesque aliquam felis condimentum tortor blandit, id feugiat sapien sollicitudin.consectetur adipiscing elit. Morbi hendrerit sollicitudin mauris, viverra gravida diam viverra ac. Donec eleifend mauris eget bibendum lacinia. Nulla pulvinar elementum risus. Mauris hendrerit gravida arcu, sit amet ultrices libero tincidunt et. Suspendisse hendrerit urna eget risus commodo porta. Vestibulum semper lorem eu urna ultrices, vel rhoncus elit feugiat. Praesent cursus velit gravida ante porttitor, sed tempor nisl tristique. Vivamus sit amet rhoncus orci, eu porttitor quam. Aenean vitae mi placerat metus posuere imperdiet quis quis risus. Maecenas at efficitur lectus. Proin eget leo volutpat mauris laoreet posuere a in lacus. Donec massa libero, condimentum non tellus quis, ornare molestie libero. Donec mattis ante non fringilla posuere. Suspendisse sagittis semper neque vitae finibus. Pellentesque aliquam felis condimentum tortor blandit, id feugiat sapien sollicitudin.</i></p>



        <p><i>The end.</i></p>
        </>
    )
}